# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91bb6b8bcd03524b316a75219357804634edf67402312765edb19949e7585d90818da5f1313fd0810bc4162941b6585891a58cdf04f6c77b8106f261e99621ad

test:
  secret_key_base: aa4eb49577d84bc9c3a1e8ae7b122816d55a6a9a60ec35435949e3e962fe1e1cf14f90226b7656f467021235acdb452bd8cf3c33df367174325ab3a32adc34e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
